### ISSUE TITLE
Vendored feature is failing to build the dependencies

### ISSUE THREAD

**Issue by superrnovae** [jkcoxson/rusty_libimobiledevice#1]
I am trying to build netmuxd from source, it depends on rusty_libimobiledevice's vendored feature, so when it's pulling in the dependencies to compile, it fails on the first one (libplist) with the following backtrace:

--- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /usr/share/cargo/registry/plist_plus-0.1.0/build.rs:90:78
  stack backtrace:
     0:     0x55d79f00251c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2afed960fc1b4464
     1:     0x55d79f02170c - core::fmt::write::h597fbc5aa1ac45ee
     2:     0x55d79effe335 - std::io::Write::write_fmt::h9493c50d61a85999
     3:     0x55d79f0040f0 - std::panicking::default_hook::{{closure}}::hd30bc046ab258a36
     4:     0x55d79f003ca9 - std::panicking::default_hook::hb9f1eb191641bdc9
     5:     0x55d79f004726 - std::panicking::rust_panic_with_hook::hb9d236646af55711
     6:     0x55d79f004480 - std::panicking::begin_panic_handler::{{closure}}::h14434cbcabaa4cba
     7:     0x55d79f0029b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h26bd53be421671f5
     8:     0x55d79f0041e9 - rust_begin_unwind
     9:     0x55d79efc36a1 - core::panicking::panic_fmt::hdf3d63a0638a18f3
    10:     0x55d79efc3733 - core::result::unwrap_failed::h132b9db788875a4e
    11:     0x55d79efc653b - core::result::Result<T,E>::unwrap::hc148c63c45eb5e5d
                                 at /builddir/build/BUILD/rustc-1.59.0-src/library/core/src/result.rs:1018:23
    12:     0x55d79efc653b - build_script_build::repo_setup::ha29a1acef689fbc4
                                 at /usr/share/cargo/registry/plist_plus-0.1.0/build.rs:90:5
    13:     0x55d79efc653b - build_script_build::main::h34b2242ea6547911
                                 at /usr/share/cargo/registry/plist_plus-0.1.0/build.rs:53:9
    14:     0x55d79efc3e83 - core::ops::function::FnOnce::call_once::h7b6ada62a662ef5d
                                 at /builddir/build/BUILD/rustc-1.59.0-src/library/core/src/ops/function.rs:227:5
    15:     0x55d79efc3e83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0e1180f921d468e5
                                 at /builddir/build/BUILD/rustc-1.59.0-src/library/std/src/sys_common/backtrace.rs:123:18
    16:     0x55d79efc3e99 - std::rt::lang_start::{{closure}}::h4c30f5ae34e731f1
                                 at /builddir/build/BUILD/rustc-1.59.0-src/library/std/src/rt.rs:145:18
    17:     0x55d79f001d1e - std::rt::lang_start_internal::hd168ff9bff1c33a1
    18:     0x55d79efc69fb - main
    19:     0x7f45ec17a590 - __libc_start_call_main
    20:     0x7f45ec17a649 - __libc_start_main_alias_2
    21:     0x55d79efc3db5 - _start
    22:                0x0 - <unknown>

**Comment by jkcoxson** [comment]
Moving this issue to plist_plus
